services:
  - type: web
    name: nguyen-truong-son-cv
    env: static
    buildCommand: "" # No build step required for static HTML
    staticPublishPath: ./ # Serves the index.html directly from root
